version: 2.1

references:
    ## Workspaces
    workspace: &workspace
                   ~/src

    ## Docker image configurations
    android_config: &android_config
        working_directory: *workspace
        docker:
            - image: circleci/android:api-30
        environment:
            TERM: dumb
            _JAVA_OPTIONS: "-Xmx2048m -XX:+UseContainerSupport"
            GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

    ## Cache
    gradle_key: &gradle_key
                    jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    gems_key: &gems_key
                  gems-{{ checksum "Gemfile.lock" }}

    restore_gradle_cache: &restore_gradle_cache
        restore_cache:
            key: *gradle_key

    restore_gems_cache: &restore_gems_cache
        restore_cache:
            key: *gems_key

    save_gradle_cache: &save_gradle_cache
        save_cache:
            key: *gradle_key
            paths:
                - ~/.gradle
                - ~/.m2

    save_gems_cache: &save_gems_cache
        save_cache:
            key: *gems_key
            paths:
                - vendor/bundle

    ## Dependencies
    ruby_dependencies: &ruby_dependencies
        run:
            name: Download Ruby Dependencies
            command: bundle check || bundle install --path vendor/bundle

    android_dependencies: &android_dependencies
        run:
            name: Download Android Dependencies
            command: ./gradlew androidDependencies

    ## Keys
    decode_android_key: &decode_android_key
        run:
            name: Decode Android key store
            command: echo $KEYSTORE | base64 -di | tee keystore.jks keystore.jks >/dev/null

    create_google_play_key: &create_google_play_key
        run:
            name: Create Google Play key
            command: echo $GOOGLE_PLAY_KEY > google_play_key.json

jobs:
    ## Deploy to Play Store
    deploy_play_store:
        <<: *android_config
        steps:
            - checkout
            - *restore_gradle_cache
            - *restore_gems_cache
            - *ruby_dependencies
            - *android_dependencies
            - *save_gradle_cache
            - *save_gems_cache
            - *decode_android_key
            - *create_google_play_key
            - run:
                  name: Deploy to Play Store
                  command: bundle exec fastlane deploy
            - store_artifacts:
                  path: app/build/outputs/bundle/
                  destination: /release/
            - store_artifacts:
                  path: app/build/outputs/mapping/
                  destination: /mapping/

workflows:
    version: 2.1
    workflow:
        jobs:
            - deploy_play_store:
                  filters:
                      branches:
                          only:
                              - master